version: '3.8'

services:
  iota-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: iota-dev-environment
    container_name: iota-dev
    volumes:
      - .:/workspace
      - cargo-cache:/root/.cargo
    working_dir: /workspace
    command: /bin/bash
    stdin_open: true
    tty: true

volumes:
  cargo-cache:
    driver: local
